import type { WebsiteConfiguration, WebsiteTemplate } from "@/lib/websites/configuration";

const themes: Record<WebsiteTemplate, { shell: string; ink: string; accent: string; soft: string; hero: string; card: string; label: string }> = {
  modern_business: { shell: "bg-[#f4f6f3]", ink: "text-[#12251e]", accent: "bg-[#d7ff72] text-[#173f35]", soft: "bg-[#e8eee9]", hero: "bg-[#173f35] text-white", card: "border-[#d6ded7] bg-white", label: "text-[#31745e]" },
  professional_corporate: { shell: "bg-[#f5f7fa]", ink: "text-[#15202b]", accent: "bg-[#e5b94b] text-[#17202a]", soft: "bg-[#e8edf3]", hero: "bg-[#17202a] text-white", card: "border-[#d6dde5] bg-white", label: "text-[#9b7115]" },
  local_service: { shell: "bg-[#fffaf2]", ink: "text-[#263126]", accent: "bg-[#2b6d5e] text-white", soft: "bg-[#f4ead8]", hero: "bg-[#f0dfc2] text-[#263126]", card: "border-[#e5d6bf] bg-white", label: "text-[#a04431]" },
};

function Logo({ configuration }: { configuration: WebsiteConfiguration }) {
  return configuration.brand.logoUrl ? (
    // eslint-disable-next-line @next/next/no-img-element -- client images are served through a controlled R2 route.
    <img src={configuration.brand.logoUrl} alt={`${configuration.identity.businessName} logo`} className="h-12 w-12 object-contain" />
  ) : <span className="flex h-11 w-11 items-center justify-center border border-current/20 text-sm font-black">{configuration.brand.monogram}</span>;
}

export function BusinessWebsiteTemplate({ configuration, isPreview = true }: { configuration: WebsiteConfiguration; isPreview?: boolean }) {
  const { identity, services, contact, online, policies, readiness, content } = configuration;
  const theme = themes[configuration.selectedTemplate] ?? themes.modern_business;
  const tel = contact.phone.replace(/[^+\d]/g, "");
  return <div className={`min-h-screen ${theme.shell} ${theme.ink}`}>
    {isPreview && !readiness.isReady ? <aside className="border-b border-amber-300 bg-amber-50 px-5 py-3 text-sm text-amber-950"><div className="mx-auto flex max-w-7xl justify-between gap-4"><strong>Draft preview</strong><span>{readiness.missing.join(", ")}</span></div></aside> : null}
    <header className="border-b border-current/10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5 px-5 py-5 sm:px-8 lg:px-12"><a href="#home" className="flex min-w-0 items-center gap-3"><Logo configuration={configuration} /><strong className="truncate text-lg">{identity.businessName}</strong></a><nav className="hidden gap-7 text-sm font-semibold md:flex"><a href="#about">About</a><a href="#services">Services</a><a href="#contact">Contact</a></nav><a href={`tel:${tel}`} className={`px-5 py-3 text-sm font-bold ${theme.accent}`}>{content.primaryCta}</a></div></header>
    <main>
      <section id="home" className={theme.hero}><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 sm:px-8 sm:py-28 lg:grid-cols-[1.35fr_0.65fr] lg:px-12"><div><p className="text-xs font-bold uppercase opacity-65">{identity.category}</p><h1 className="mt-5 max-w-4xl text-4xl leading-tight font-black sm:text-6xl lg:text-7xl">{content.heroHeadline}</h1><p className="mt-6 max-w-2xl text-lg leading-8 opacity-75">{content.heroSubheadline}</p><div className="mt-9 flex flex-wrap gap-3"><a href={`tel:${tel}`} className={`px-6 py-3.5 text-sm font-bold ${theme.accent}`}>{content.primaryCta}</a><a href={`mailto:${contact.email}`} className="border border-current/30 px-6 py-3.5 text-sm font-bold">{content.secondaryCta}</a></div></div><div className="flex min-h-64 flex-col justify-end border border-current/20 p-7"><p className="text-xs font-bold uppercase opacity-60">Serving</p><p className="mt-3 text-2xl font-bold">{contact.formattedLocation || contact.country}</p><p className="mt-7 break-all text-sm opacity-70">{contact.email}</p><p className="mt-1 text-sm opacity-70">{contact.phone}</p></div></div></section>
      <section id="about" className="bg-white"><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[0.65fr_1.35fr] lg:px-12"><div><p className={`text-xs font-bold uppercase ${theme.label}`}>About</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">About {identity.businessName}</h2></div><div><p className="text-lg leading-8 opacity-75">{content.about}</p>{identity.legalBusinessName ? <p className="mt-6 text-sm opacity-55">Legal business name: {identity.legalBusinessName}</p> : null}</div></div></section>
      <section id="services" className={`border-y border-current/10 ${theme.soft}`}><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-12"><p className={`text-xs font-bold uppercase ${theme.label}`}>Services</p><h2 className="mt-4 text-3xl font-black sm:text-4xl">How we can help</h2><div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <article key={`${service}-${index}`} className={`min-h-56 border p-7 ${theme.card}`}><span className="text-xs font-bold opacity-40">{String(index + 1).padStart(2, "0")}</span><h3 className="mt-8 text-xl font-bold">{service}</h3><p className="mt-4 text-sm leading-6 opacity-65">{content.serviceDescriptions[index] ?? `Contact ${identity.businessName} to discuss this service.`}</p></article>)}</div></div></section>
      {content.faqs.length ? <section className="bg-white"><div className="mx-auto max-w-4xl px-5 py-20 sm:px-8"><h2 className="text-3xl font-black">Frequently asked questions</h2><div className="mt-8 divide-y divide-current/10">{content.faqs.map((faq) => <details key={faq.question} className="py-5"><summary className="cursor-pointer font-bold">{faq.question}</summary><p className="mt-3 leading-7 opacity-70">{faq.answer}</p></details>)}</div></div></section> : null}
      <section id="contact" className={theme.hero}><div className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-12"><div><p className="text-xs font-bold uppercase opacity-60">Contact</p><h2 className="mt-4 text-4xl font-black">Talk with {identity.businessName}</h2><p className="mt-4 opacity-65">Contact the business directly to confirm service scope, pricing, and availability.</p></div><div className="grid gap-3 sm:grid-cols-2"><a href={`tel:${tel}`} className="border border-current/20 p-5"><small className="block opacity-50">Phone</small><strong className="mt-2 block">{contact.phone}</strong></a><a href={`mailto:${contact.email}`} className="border border-current/20 p-5"><small className="block opacity-50">Email</small><strong className="mt-2 block break-all">{contact.email}</strong></a><div className="border border-current/20 p-5 sm:col-span-2"><small className="block opacity-50">Location</small><strong className="mt-2 block">{contact.formattedLocation}</strong></div></div></div></section>
      <section className="bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-5 px-5 py-10 sm:px-8 lg:px-12"><strong>Connect with {identity.businessName}</strong><div className="flex gap-3">{online.facebook ? <a href={online.facebook} target="_blank" rel="noreferrer" className="border border-current/20 px-4 py-2 text-sm font-bold">Facebook</a> : null}{online.instagram ? <a href={online.instagram} target="_blank" rel="noreferrer" className="border border-current/20 px-4 py-2 text-sm font-bold">Instagram</a> : null}</div></div></section>
      {[{ id: "privacy", title: "Privacy Policy", copy: policies.privacy }, { id: "terms", title: "Terms of Service", copy: policies.terms }].map((policy) => <section key={policy.id} id={policy.id} className="border-t border-current/10"><div className="mx-auto grid max-w-7xl gap-6 px-5 py-14 sm:px-8 lg:grid-cols-[0.5fr_1.5fr] lg:px-12"><h2 className="text-2xl font-black">{policy.title}</h2><div className="space-y-3 text-sm leading-7 opacity-65">{policy.copy.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div></div></section>)}
    </main>
    <footer className={`${theme.hero} border-t border-current/10`}><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-5 px-5 py-9 sm:px-8 lg:px-12"><strong>{identity.businessName}</strong><div className="flex gap-5 text-sm opacity-65"><a href="#privacy">Privacy</a><a href="#terms">Terms</a>{online.preferredDomain ? <span>{online.preferredDomain}</span> : null}</div></div></footer>
  </div>;
}