"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { DomainRecord } from "@/lib/domains/repository";
import { getNextSetupOperation } from "@/lib/domains/setup-sequence";

type Step = { label: string; status: "not_started" | "pending" | "ready" | "warning" | "failed" };
export function SetupPanel({ clientId, preferredDomain, domain, hasWebsite, aiSuccess }: { clientId: string; preferredDomain: string; domain: DomainRecord | null; hasWebsite: boolean; aiSuccess: boolean }) {
  const router = useRouter(); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [meta, setMeta] = useState(domain?.metaVerificationValue ?? "");
  const [purchaseConfirmation, setPurchaseConfirmation] = useState(""); const [confirmationToken, setConfirmationToken] = useState("");
  const [itemId, setItemId] = useState(""); const [paymentMethodId, setPaymentMethodId] = useState(""); const [whoisId, setWhoisId] = useState(""); const [secondConfirmation, setSecondConfirmation] = useState(false);
  const steps: Step[] = [
    { label: "Business Details", status: preferredDomain ? "ready" : "warning" }, { label: "Website", status: hasWebsite ? "ready" : "not_started" },
    { label: "AI Content", status: aiSuccess ? "ready" : hasWebsite ? "warning" : "not_started" }, { label: "Domain", status: domain ? "ready" : "not_started" },
    { label: "Domain Ownership", status: domain?.ownershipStatus === "purchased" || domain?.ownershipStatus === "existing_owned_domain" ? "ready" : domain?.ownershipStatus === "purchase_pending" ? "pending" : "not_started" },
    { label: "Cloudflare Zone", status: domain?.cloudflareZoneStatus === "active" ? "ready" : domain?.cloudflareZoneStatus === "failed" ? "failed" : "not_started" },
    { label: "Nameservers", status: domain?.nameserverStatus === "configured" ? "ready" : domain?.nameserverStatus === "pending" ? "pending" : "not_started" }, { label: "Worker Domain", status: domain?.customDomainStatus === "active" ? "ready" : domain?.customDomainStatus === "pending" ? "pending" : "not_started" },
    { label: "HTTPS", status: domain?.sslStatus === "ready" ? "ready" : "not_started" }, { label: "Meta TXT", status: domain?.metaPublicDnsStatus === "dns_detected" ? "ready" : domain?.metaVerificationStatus === "record_created" ? "pending" : "not_started" },
  ];
  async function run(operation: string, extra: Record<string, unknown> = {}) { setBusy(true); setMessage(""); const response = await fetch(`/api/clients/${clientId}/setup`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ operation, ...extra }) }); const result = await response.json() as { message?: string; error?: string; confirmationToken?: string }; setBusy(false); setMessage(result.message ?? result.error ?? "Operation complete."); if (result.confirmationToken) setConfirmationToken(result.confirmationToken); router.refresh(); }
  const next = getNextSetupOperation(domain);
  return <section className="mt-6 border border-slate-200 bg-white p-6 sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Setup pipeline</h2><p className="mt-1 text-sm text-slate-500">Continue advances only the next non-paid operation.</p></div>{!(["complete", "check_domain", "ownership_required"] as string[]).includes(next) ? <button disabled={busy} onClick={() => run(next)} className="bg-slate-950 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Continue setup</button> : null}{next === "check_domain" && preferredDomain ? <button disabled={busy} onClick={() => run("check_domain", { domain: preferredDomain })} className="bg-slate-950 px-4 py-2 text-sm font-bold text-white">Check domain</button> : null}</div>
    <div className="mt-6 grid gap-px bg-slate-200 sm:grid-cols-2 lg:grid-cols-5">{steps.map((step) => <div key={step.label} className="bg-white p-3"><p className="text-xs font-bold text-slate-500">{step.label}</p><p className={`mt-1 text-xs font-semibold ${step.status === "ready" ? "text-emerald-700" : step.status === "failed" ? "text-red-700" : step.status === "warning" ? "text-amber-700" : "text-slate-400"}`}>{step.status.replace("_", " ")}</p></div>)}</div>
    {domain?.availabilityStatus === "available" && domain.purchaseStatus !== "purchased" ? <div className="mt-5 border-t border-slate-200 pt-5"><h3 className="text-sm font-bold text-slate-800">Paid domain registration</h3><p className="mt-1 text-xs text-slate-500">Registration is separate from Continue setup and requires two explicit confirmations.</p>{!confirmationToken ? <div className="mt-3 flex flex-col gap-3 sm:flex-row"><input value={purchaseConfirmation} onChange={(event) => setPurchaseConfirmation(event.target.value)} placeholder={`Type ${domain.domain}`} className="min-w-0 flex-1 border border-slate-300 px-3 py-2 text-sm" /><button disabled={busy || purchaseConfirmation !== domain.domain} onClick={() => run("confirm_purchase", { confirmation: purchaseConfirmation })} className="border border-red-300 px-4 py-2 text-sm font-bold text-red-700 disabled:opacity-40">Confirm purchase intent</button></div> : <div className="mt-3 grid gap-3 sm:grid-cols-3"><input value={itemId} onChange={(event) => setItemId(event.target.value)} placeholder="Hostinger item ID" className="border border-slate-300 px-3 py-2 text-sm" /><input value={paymentMethodId} onChange={(event) => setPaymentMethodId(event.target.value)} placeholder="Payment method ID" className="border border-slate-300 px-3 py-2 text-sm" /><input value={whoisId} onChange={(event) => setWhoisId(event.target.value)} inputMode="numeric" placeholder="WHOIS profile ID" className="border border-slate-300 px-3 py-2 text-sm" /><label className="flex items-center gap-2 text-sm sm:col-span-2"><input type="checkbox" checked={secondConfirmation} onChange={(event) => setSecondConfirmation(event.target.checked)} />I explicitly approve this paid registration</label><button disabled={busy || !secondConfirmation || !itemId || !paymentMethodId || !/^\d+$/.test(whoisId)} onClick={() => run("purchase_domain", { confirmationToken, secondConfirmation, itemId, paymentMethodId, whoisId: Number(whoisId) })} className="bg-red-700 px-4 py-2 text-sm font-bold text-white disabled:opacity-40">Submit paid registration</button></div>}</div> : null}
    {domain?.cloudflareZoneId ? <div className="mt-5 flex flex-col gap-3 sm:flex-row"><input value={meta} onChange={(event) => setMeta(event.target.value)} placeholder="facebook-domain-verification=..." className="min-w-0 flex-1 border border-slate-300 px-3 py-2 text-sm" /><button disabled={busy || !meta} onClick={() => run("create_meta_txt", { value: meta })} className="border border-slate-300 px-4 py-2 text-sm font-bold">Create Meta TXT</button></div> : null}
    {domain?.metaVerificationStatus === "record_created" ? <button disabled={busy} onClick={() => run("check_meta_txt")} className="mt-3 border border-slate-300 px-4 py-2 text-sm font-bold">Check public DNS</button> : null}
    {domain?.metaPublicDnsStatus === "dns_detected" ? <p className="mt-3 text-sm font-semibold text-emerald-700">DNS detected. Ready to verify in Meta.</p> : null}
    {message ? <p className="mt-4 text-sm text-slate-600" role="status">{message}</p> : null}
  </section>;
}